### PR TITLE
Allow professionals to be >28 years old

### PR DESCRIPTION
**Pull request by SolalPirelli**
Change suggested by Christian, to allow former participants who turned 29 to participate again.  
Jakub adds that this might cause EPFL professors to participate, which would be fun.

### CODE REVIEW

**Comment by SolalPirelli** [comment]
This causes another question: Do we want to allow students who are >28 years old? I know a few people who are older than the average for various reasons (career choices, early failure in school, ..), but they most likely wouldn't be better than your average student at this contest.

Here's a suggestion: Define students as "people who are currently studying, and haven't yet got a Master's degree (in any field)".

What do you think?

**Comment by tharvik** [comment]
I'm in favor of having a more general definition of student, as @SolalPirelli stated, not limited to age.

**Comment by Rabyss** [comment]
I would say "people who are currently studying, and haven't yet got a Master's degree (in any computer science related field)" because some Master's degree are useless to have in a programming competition.

**Comment by SolalPirelli** [comment]
I thought about this formulation, but it has two problems:

* It's hard to define "related to CS" precisely (especially when you start including minors and other funky stuff).
* Many degrees involve some programming nowadays, and algorithms which might be thought of as CS-only often find far-reaching applications.

IMHO it's fine if we have the occasional problematic case like "I got a Master's in French linguistics, but I'm currently a bachelor in CS, so that makes me a professional!?" or whatever.

**Comment by Rabyss** [comment]
This is true, we can do this like this then.

**Pull request merged**
